<?php

/**
 * @file
 * Contains hooks for Migrations Block module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrations_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the Migrations Block module.
    case 'help.page.migrations_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The module provides Migrations Block functionality.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function migrations_block_theme($existing, $type, $theme, $path) {
  return [
    'migrations_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'block--migrations',
    ],
  ];
}
