<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function loan_amortization_theme($theme) {
  $theme['loan_summary'] = [
    'variables' => [
      'loan_summary' => NULL,
      'loan_labels' => NULL,
    ],
  ];
  $theme['loan_payments'] = [
    'variables' => [
      'loan_payments' => NULL,
      'payment_labels' => NULL,
    ],
  ];

  return $theme;
}

/**
 * Implements hook_help().
 */
function loan_amortization_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.loan_amortization':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }

  return NULL;
}
